<?php

declare(strict_types=1);

namespace Dbp\Relay\BlobBundle\DependencyInjection;

use Dbp\Relay\CoreBundle\Authorization\AuthorizationConfigDefinition;
use Dbp\Relay\CoreBundle\Rest\Rest;
use Symfony\Component\Config\Definition\Builder\NodeDefinition;
use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    public const ROLE_METADATABACKUPS = 'ROLE_METADATABACKUPS';
    public const ROLE_PROFILE_METADATABACKUPS = 'ROLE_PROFILE_METADATABACKUPS';

    private function getAuthNode(): NodeDefinition
    {
        return AuthorizationConfigDefinition::create()
            ->addRole(self::ROLE_METADATABACKUPS, 'false', 'Returns true if the user is allowed to access middleware API.')
            ->getNodeDefinition();
    }

    public const DATABASE_URL = 'database_url';

    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('dbp_relay_blob');

        $treeBuilder->getRootNode()->append(Rest::getConfigNodeDefinition());

        $treeBuilder
            ->getRootNode()
                ->children()
                    ->scalarNode(self::DATABASE_URL)
                        ->isRequired()
                        // ->cannotBeEmpty()
                        ->defaultValue('%env(resolve:BLOB_DATABASE_NAME)%')
                    ->end()
                    ->scalarNode('reporting_interval')
                        ->isRequired()
                        ->defaultValue('0 9 * * MON')
                    ->end()
                    ->scalarNode('quota_warning_interval')
                        ->isRequired()
                        ->defaultValue('0 6 * * *')
                    ->end()
                    ->scalarNode('cleanup_interval')
                        ->isRequired()
                        ->defaultValue('0 * * * *')
                    ->end()
                    ->scalarNode('file_integrity_checks')
                        ->isRequired()
                        ->defaultValue(false)
                    ->end()
                    ->scalarNode('additional_auth')
                        ->isRequired()
                        ->defaultValue(false)
                    ->end()
                    ->scalarNode('filedata_schema')
                        ->isRequired()
                        ->defaultValue('%kernel.project_dir%/vendor/dbp/relay-blob-bundle/src/Resources/filedata-v1.schema.json')
                    ->end()
                    ->scalarNode('integrity_check_interval')
                        ->isRequired()
                        ->defaultValue('0 0 1 * *')
                    ->end()
                    ->scalarNode('bucket_size_check_interval')
                        ->isRequired()
                        ->defaultValue('0 2 * * 1')
                    ->end()
                    ->arrayNode('buckets')
                        ->isRequired()
                        ->cannotBeEmpty()
                        ->arrayPrototype()
                            ->children()
                                ->scalarNode('service')
                                    ->isRequired()
                                    ->cannotBeEmpty()
                                ->end()
                                ->scalarNode('internal_bucket_id')
                                    ->isRequired()
                                    ->cannotBeEmpty()
                                ->end()
                                ->scalarNode('bucket_id')
                                    ->isRequired()
                                    ->cannotBeEmpty()
                                ->end()
                                ->scalarNode('key')
                                    ->isRequired()
                                    ->cannotBeEmpty()
                                ->end()
                                ->scalarNode('quota')
                                    ->isRequired()
                                    ->cannotBeEmpty()
                                ->end()
                                ->scalarNode('output_validation')
                                    ->isRequired()
                                    ->defaultValue(true)
                                ->end()
                                ->scalarNode('notify_when_quota_over')
                                    ->isRequired()
                                    ->cannotBeEmpty()
                                ->end()
                                ->scalarNode('report_when_expiry_in')
                                    ->isRequired()
                                    ->cannotBeEmpty()
                                ->end()
                                ->scalarNode('bucket_owner')
                                    ->isRequired()
                                    ->cannotBeEmpty()
                                ->end()
                                ->scalarNode('link_expire_time')
                                    ->isRequired()
                                    ->defaultValue('PT1M')
                                ->end()
                                ->arrayNode('warn_quota')
                                    ->children()
                                        ->scalarNode('dsn')
                                        ->end()
                                        ->scalarNode('from')
                                        ->end()
                                        ->scalarNode('to')
                                        ->end()
                                        ->scalarNode('subject')
                                        ->end()
                                        ->scalarNode('html_template')
                                        ->defaultValue('emails/warn-quota.html.twig')
                                        ->end()
                                    ->end()
                                ->end()
                                ->arrayNode('reporting')
                                    ->children()
                                        ->scalarNode('dsn')
                                        ->end()
                                        ->scalarNode('from')
                                        ->end()
                                        ->scalarNode('to')
                                        ->end()
                                        ->scalarNode('subject')
                                        ->end()
                                        ->scalarNode('html_template')
                                        ->defaultValue('emails/reporting.html.twig')
                                        ->end()
                                    ->end()
                                ->end()
                                ->arrayNode('integrity')
                                    ->children()
                                        ->scalarNode('dsn')
                                        ->end()
                                        ->scalarNode('from')
                                        ->end()
                                        ->scalarNode('to')
                                        ->end()
                                        ->scalarNode('subject')
                                        ->end()
                                        ->scalarNode('html_template')
                                        ->defaultValue('emails/integrity.html.twig')
                                        ->end()
                                    ->end()
                                ->end()
                                ->arrayNode('bucket_size')
                                    ->children()
                                        ->scalarNode('dsn')
                                        ->end()
                                        ->scalarNode('from')
                                        ->end()
                                        ->scalarNode('to')
                                        ->end()
                                        ->scalarNode('subject')
                                        ->end()
                                        ->scalarNode('html_template')
                                        ->defaultValue('emails/bucketsize.html.twig')
                                        ->end()
                                    ->end()
                                ->end()
                                ->arrayNode('additional_types')
                                    ->useAttributeAsKey('name')
                                    ->arrayPrototype()
                                        ->children()
                                            ->scalarNode('json_schema_path')
                                            ->end()
                                            ->scalarNode('verity_profile')
                                            ->end()
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->append($this->getAuthNode())
            ->end();

        return $treeBuilder;
    }
}
