resources:
  Dbp\Relay\BlobBundle\Entity\FileData:
    types: ['https://schema.org/DigitalDocument']
    shortName: "BlobFiles"
    routePrefix: "/blob"
    normalizationContext:
      groups: ["BlobFiles:output"]
      jsonld_embed_context: true
    denormalizationContext:
      groups: ["BlobFiles:input"]

    operations:

      ApiPlatform\Metadata\GetCollection:
        security: 'is_granted("IS_AUTHENTICATED_FULLY")'
        provider: Dbp\Relay\BlobBundle\State\FileDataProvider
        uriTemplate: "/files"
        normalizationContext:
          groups: ["BlobFiles:output"]
          jsonld_embed_context: true
        openapiContext:
          tags: ["Blob"]
          summary: "Get the fileshares of a specific bucket with a specific prefix"
          parameters:
            - name: bucketID
              in: query
              description: 'Identifier of bucket'
              type: string
              required: true
              example: "1234"
            - name: creationTime
              in: query
              description: 'Current time in ISO 8601'
              type: string
              required: true
              example: "2019-09-07T-15:50+00"
            - name: prefix
              in: query
              description: 'Prefix of a file collection'
              type: string
              required: true
              example: "my-prefix/my-subprefix"
            - name: method
              in: query
              description: 'method that gets executed'
              type: string
              required: true
              example: "GET"
            - name: includeData
              in: query
              description: 'If the returned contentUrl is a http link or the base64 encoded data'
              type: string
              required: false
              example: "1"
            - name: sig
              in: query
              description: 'Signature containing the checksum required for the check'
              type: string
              required: true
              example: ""

      ApiPlatform\Metadata\Get:
        security: 'is_granted("IS_AUTHENTICATED_FULLY")'
        provider: Dbp\Relay\BlobBundle\State\FileDataProvider
        uriTemplate: "/files/{identifier}"
        openapiContext:
          tags: ["Blob"]
          summary: "Get the fileshare of a specific bucket with a specific prefix and a specific id"
          parameters:
            - name: bucketID
              in: query
              description: 'Identifier of bucket'
              type: string
              required: true
              example: "1234"
            - name: creationTime
              in: query
              description: 'Current time in ISO 8601'
              type: string
              required: true
              example: "2019-09-07T-15:50+00 "
            - name: prefix
              in: query
              description: 'Prefix of a file collection'
              type: string
              required: true
              example: "my-prefix/my-subprefix"
            - name: method
              in: query
              description: 'method that gets executed'
              type: string
              required: true
              example: "GET"
            - name: includeData
              in: query
              description: 'If the returned contentUrl is a http link or the base64 encoded data'
              type: string
              required: false
              example: "1"
            - name: sig
              in: query
              description: 'Signature containing the checksum required for the check'
              type: string
              required: true
              example: ""

      ApiPlatform\Metadata\Delete:
        security: 'is_granted("IS_AUTHENTICATED_FULLY")'
        provider: Dbp\Relay\BlobBundle\State\FileDataProvider
        processor: Dbp\Relay\BlobBundle\State\FileDataProcessor
        uriTemplate: "/files/{identifier}"
        denormalizationContext:
          groups: ["BlobFiles:exists"]
        openapiContext:
          tags: ["Blob"]
          summary: "Delete a fileshare of a specific bucket with a specific prefix and a specific id"
          parameters:
            - name: bucketID
              in: query
              description: 'Identifier of bucket'
              type: string
              required: true
              example: "1234"
            - name: creationTime
              in: query
              description: 'Current times as ISO 8601'
              type: string
              required: true
              example: "2019-09-07T-15:50+00 "
            - name: prefix
              in: query
              description: 'Prefix of a file collection'
              type: string
              required: true
              example: "my-prefix/my-subprefix"
            - name: method
              in: query
              description: 'method that gets executed'
              type: string
              required: true
              example: "DELETE"
            - name: sig
              in: query
              description: 'Signature containing the checksum required for the check'
              type: string
              required: true
              example: ""

      ApiPlatform\Metadata\Patch:
        security: 'is_granted("IS_AUTHENTICATED_FULLY")'
        provider: Dbp\Relay\BlobBundle\State\FileDataProvider
        processor: Dbp\Relay\BlobBundle\State\FileDataProcessor
        uriTemplate: "/files/{identifier}"
        denormalizationContext:
          groups: ["BlobFiles:update"]

        openapiContext:
          tags: ["Blob"]
          parameters:
            - name: bucketID
              in: query
              description: 'Identifier of bucket'
              type: string
              required: true
              example: "1234"
            - name: creationTime
              in: query
              description: 'Current time as ISO 8601'
              type: string
              required: true
              example: "2019-09-07T-15:50+00 "
            - name: prefix
              in: query
              description: 'Prefix of a file collection'
              type: string
              required: true
              example: "my-prefix/my-subprefix"
            - name: method
              in: query
              description: 'method that gets executed'
              type: string
              required: true
              example: "PATCH"
            - name: fileName
              in: query
              description: 'New filename'
              type: string
              required: true
              example: ""
            - name: sig
              in: query
              description: 'Signature containing the checksum required for the check'
              type: string
              required: true
              example: ""

      ApiPlatform\Metadata\Post:
        security: 'is_granted("IS_AUTHENTICATED_FULLY")'
        controller: Dbp\Relay\BlobBundle\Controller\CreateFileDataAction
        uriTemplate: "/files"
        deserialize: false
        openapiContext:
          tags: ["Blob"]
          parameters:
            - name: bucketID
              in: query
              description: 'Identifier of bucket'
              type: string
              required: true
              example: "1234"
            - name: creationTime
              in: query
              description: 'Current time as ISO 8601'
              type: string
              required: true
              example: "2019-09-07T-15:50+00 "
            - name: prefix
              in: query
              description: 'Prefix of a file collection'
              type: string
              required: true
              example: "my-prefix/my-subprefix"
            - name: method
              in: query
              description: 'method that gets executed'
              type: string
              required: true
              example: "GET"
            - name: fileName
              in: query
              description: 'Name of the file to upload'
              type: string
              required: true
              example: "test.txt"
            - name: fileHash
              in: query
              description: 'Hash of the file to upload'
              type: string
              required: true
              example: ""
            - name: sig
              in: query
              description: 'Signature containing the checksum required for the check'
              type: string
              required: true
              example: ""
            - name: retentionDuration
              in: query
              description: 'Max time in timestamp duration in ISO 8601 format from creation date when file will be deleted'
              type: string
              required: false
              example: "P2YT6H"
            - name: notifyEmail
              in: query
              description: 'An email address which gets notified before the files expires'
              type: string
              required: false
              example: "test@test.com"
            - name: additionalMetadata
              in: query
              description: 'Additional Metadata for the file'
              type: object
              required: false
              example: "my File additional Data"
          requestBody:
            content:
              multipart/form-data:
                schema:
                  type: "object"
                  required: ["file", "bucketID"]
                  properties:
                    file:
                      type: "string"
                      format: "binary"
                    prefix:
                      description: "Prefix of the file"
                      type: "string"
                      example: "my-prefix/my-subprefix"
                    fileName:
                      description: "Friendly name of the file"
                      type: "string"
                      example: "myfile"
                    bucketID:
                      description: "ID of the bucket"
                      type: "string"
                      example: "1234"

      delete_byPrefix:
        security: 'is_granted("IS_AUTHENTICATED_FULLY")'
        class: ApiPlatform\Metadata\Delete
        method: DELETE
        controller: Dbp\Relay\BlobBundle\Controller\DeleteFileDatasByPrefix
        uriTemplate: "/files"
        normalizationContext:
          groups: ["BlobFiles:output"]
          jsonld_embed_context: true
        read: false
        openapiContext:
          tags: ["Blob"]
          summary: "Deletes the files of a specific bucket with a specific prefix"
          parameters:
            - name: bucketID
              in: query
              description: 'Identifier of bucket'
              type: string
              required: true
              example: "1234"
            - name: creationTime
              in: query
              description: 'Current time as ISO 8601'
              type: string
              required: true
              example: "2019-09-07T-15:50+00 "
            - name: prefix
              in: query
              description: 'Prefix of a file collection'
              type: string
              required: true
              example: "my-prefix/my-subprefix"
            - name: method
              in: query
              description: 'method that gets executed'
              type: string
              required: true
              example: "DELTEALL"
            - name: sig
              in: query
              description: 'Signature containing the checksum required for the check'
              type: string
              required: true
              example: ""

      download:
        security: 'is_granted("IS_AUTHENTICATED_FULLY")'
        class: ApiPlatform\Metadata\Get
        method: GET
        controller: Dbp\Relay\BlobBundle\Controller\DownloadAction
        uriTemplate: "/files/{identifier}/download"
        normalizationContext:
          groups: ["BlobFiles:output"]
          jsonld_embed_context: true
        read: false
        openapiContext:
          tags: ["Blob"]
          summary: "Returns the file with given identifier as a binary response"
          parameters:
            - name: bucketID
              in: query
              description: 'Identifier of bucket'
              type: string
              required: true
              example: "1234"
            - name: creationTime
              in: query
              description: 'Current time as ISO 8601'
              type: string
              required: true
              example: "2019-09-07T-15:50+00 "
            - name: method
              in: query
              description: 'method that gets executed'
              type: string
              required: true
              example: "GET"
            - name: sig
              in: query
              description: 'Signature containing the checksum required for the check'
              type: string
              required: true
              example: ""

    properties:
      identifier:
        identifier: true
        iri: "http://schema.org/identifier"
      prefix:
        iri: "https://schema.org/Text"
      fileName:
        iri: "https://schema.org/name"
      bucketID:
        iri: "https://schema.org/identifier"
      dateCreated:
        iri: "https://schema.org/dateCreated"
      lastAccess:
        iri: "https://schema.org/dateRead"
      retentionDuration:
        iri: "https://schema.org/duration"
      existsUntil:
        iri: "https://schema.org/expires"
      contentUrl:
        iri: "https://schema.org/url"
      additionalMetadata:
        iri: "https://schema.org/DataFeed"
      fileSize:
        iri: "https://schema.org/contentSize"
      notifyEmail:
        iri: "https://schema.org/email"