services:
  Dbp\Relay\BlobBundle\Service\BlobService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobBundle\Controller\:
    tags: [ 'controller.service_arguments' ]
    resource: '../../Controller'
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobBundle\Service\ConfigurationService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobBundle\Service\DatasystemProviderService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobBundle\DataProvider\:
    resource: '../../DataProvider'
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobBundle\DataPersister\:
    resource: '../../DataPersister'
    autowire: true
    autoconfigure: true
