services:
  Dbp\Relay\BlobBundle\Service\BlobService:
    autowire: true
    autoconfigure: true
    arguments:
      $em: '@doctrine.orm.dbp_relay_blob_bundle_entity_manager'

  Dbp\Relay\BlobBundle\Service\BlobChecks:
    autowire: true
    autoconfigure: true
    arguments:
      $em: '@doctrine.orm.dbp_relay_blob_bundle_entity_manager'

  Dbp\Relay\BlobBundle\Controller\:
    tags: [ 'controller.service_arguments' ]
    resource: '../../Controller'
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobBundle\Service\ConfigurationService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobBundle\Service\DatasystemProviderService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobBundle\Service\HealthCheck:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobBundle\State\:
    resource: '../../State'
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobBundle\Cron\CleanupCronJob:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobBundle\Cron\SendReportCronJob:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobBundle\Cron\IntegrityCronJob:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobBundle\Cron\BucketSizeCronJob:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobBundle\Cron\SendQuotaWarningCronJob:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobBundle\Command\:
    resource: '../../Command'
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobBundle\Api\FileApi:
    autowire: true
    autoconfigure: true
