services:
  Dbp\Relay\BlobBundle\Service\BlobService:
    autowire: true
    autoconfigure: true
    arguments:
      $entityManager: '@doctrine.orm.dbp_relay_blob_bundle_entity_manager'

  Dbp\Relay\BlobBundle\Service\BlobChecks:
    autowire: true
    autoconfigure: true
    arguments:
      $entityManager: '@doctrine.orm.dbp_relay_blob_bundle_entity_manager'

  Dbp\Relay\BlobBundle\Service\BlobUpdates:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobBundle\Configuration\ConfigurationService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobBundle\Service\DatasystemProviderService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobBundle\Service\HealthCheck:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobBundle\ApiPlatform\:
    resource: '../../ApiPlatform'
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobBundle\Cron\:
    resource: '../../Cron'
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobBundle\Command\:
    resource: '../../Command'
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobBundle\Api\FileApi:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BlobBundle\TestUtils\TestDatasystemProviderService:
    autowire: true
    autoconfigure: true
